### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by qq99**
screen shot 2014-03-07 at 2 58 23 pm
screen shot 2014-03-07 at 2 59 54 pm
and I'll go through the rest and make it reasonable

### CODE REVIEW

**Comment by qq99** [comment]
screen shot 2014-03-20 at 3 58 29 pm
It's XSS proof, added a basic breadcrumb to bring you to project#show

**Comment by qq99** [comment]
@karlhungus @kmcphillips @ibawt :shipit:?

**Comment by ibawt** [comment]
I don't have time to test, if it works I trust you!

**Comment by kmcphillips** [comment]
:baby_bottle::baby:

**Comment by qq99** [comment]
@ibawt sorry to ping you, feel free to disregard :)

**Pull request merged**
