### PR TITLE
be save on initital state with project column headers

### PR DESCRIPTION
**Pull request by karlhungus**

### CODE REVIEW

**Comment by ibawt** [comment]
I think this should be pulled out into a view helper instead.

**Comment by karlhungus** [comment]
I'll fix it. I've been kind of continuing to follow the hack days mind set, should I be backing off that (ie tests, prettier code?

**Comment by ibawt** [comment]
Hackdays are over, we're going to do it right now.  I've got a bunch of issues in the thing now.  Rspec is set up , getting travis ready now.

**Comment by karlhungus** [comment]
ok, non hack day code :). Sorry it took so long, been a busy week. Let me know if there's something else needs doing.

**Comment by karlhungus** [comment]
reping @ibawt you mind taking a peek at this one? it's been so long i'm not sure it's useful anymore

**Comment by karlhungus** [comment]
Pretty low value even if useful.

**Pull request closed without merging**
